### ISSUE TITLE
Server side UI improvement

### ISSUE THREAD

**Issue by PovelikinRostislav** [PovelikinRostislav/client_server_app#18]
Надо разработать UI на стороне сервера
Подробности можно увидеть в описании второго milestone

**Comment by PovelikinRostislav** [comment]
Кнопка exit ничего не делает:  не завершает программу, а окно - становится неактивным (но не виснет)

**Comment by PovelikinRostislav** [comment]
Нет вертикального скролла оконном менеджере - нельзя смотреть логи

**Comment by PovelikinRostislav** [comment]
При закрытии окна на крестик - серверное приложение НЕ останавливается, а продолжает работу, судя по IDE

**Comment by PovelikinRostislav** [comment]
Результат нажатия кнопки стоп сервер (ничего) : 
![image](https://cloud.githubusercontent.com/assets/20692004/24193107/2536f7d0-0f02-11e7-8d47-5c3e1c2a820e.png)

**Comment by komarovn** [comment]
Done
