### ISSUE TITLE
Ответить на комментарии Никиты

### ISSUE THREAD

**Issue by PovelikinRostislav** [PovelikinRostislav/client_server_app#20]

**Comment by komarovn** [comment]
Done.

**Comment by PovelikinRostislav** [comment]
Not fully answered

**Comment by komarovn** [comment]
My answers are absolutely full.
Issue is closed.

**Comment by nik709** [comment]
Что делает данная анатация?
Разберёмся вместе.
При регистрации контроллера в .fxml файле заполняются поля контроллера.
Как они заполняются, если они private? 
Очень просто: для этого вызывается метод setAccessible(boolean bool).
Данный метод является привелигированным и может быть вызван только в безопасном контекстен.
И, разумеется, данный контекст может нарушиться. После этого поля, помеченные аннотацией @FXML перестанут инициализироваться. Какие будут из этого последствия вы и сами знаете.

Спасибо за ответы!

**Comment by komarovn** [comment]
@nik709, thanks!
