### ISSUE TITLE
Message classification

### ISSUE THREAD

**Issue by komarovn** [PovelikinRostislav/client_server_app#27]
Сделать типизацию реквестов-респонсов.

**Comment by komarovn** [comment]
Нашел паттерн "Абстрактная фабрика": https://www.youtube.com/watch?v=ub0DXaeV6hA
На мой взгляд, паттерн удовлетворяет нашим целям по обработке запросов и ответов разных типов. Тип сообщения узнается в режиме рантайм. Нам надо определить, какой класс/метод для обработки использовать.

**Comment by komarovn** [comment]
Более сложная реализация для паттерна "Абстрактная фабрика": https://www.youtube.com/watch?v=xbjAsdAK4xQ
Это просто для справки, если интересно будет, посмотри. Нам скорее всего хватит обычной Фабрики.

**Comment by PovelikinRostislav** [comment]
https://ru.m.wikipedia.org/wiki/%D0%90%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%B0%D1%8F_%D1%84%D0%B0%D0%B1%D1%80%D0%B8%D0%BA%D0%B0_%28%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%29?wprov=sfla1

**Comment by PovelikinRostislav** [comment]
На Вики так же присутствует​ статья для понимания 
Показалась адекватной. 

Единственное- мы вновь будем дублировать код, создавая тот же класс и в сервере и в клиенте?

**Comment by PovelikinRostislav** [comment]
Done.
