### ISSUE TITLE
Server side CPU/RAM consumption

### ISSUE THREAD

**Issue by PovelikinRostislav** [PovelikinRostislav/client_server_app#29]
Даже остановив сервер - приложение жрет до 100% CPU (пока свободного не останется)

**Comment by komarovn** [comment]
Надо провести расследование. Одна из возможных причин - условие у вечных циклов.
Надо заменить конструкции `socket.isClosed()` на обычные булевские флаги.

**Comment by komarovn** [comment]
Провел исследование. Выяснил, что загрузка CPU до 100% происходит в результате вечных циклов.
ServerThread - работает нормально (за счет блокирующего метода accept).
SchedulerThread - необходимо исправить while(true). Нагрузка на CPU возрастает до 40-50% при ничего не выполняющем полезного потоке.

**Comment by komarovn** [comment]
На стороне клиента есть 2 потока:
**RequestThread** - получаем вечный цикл, откуда загруженность CPU до 30%.
**ResponseThread** - работает нормально, так как осуществлен блокирующий вызов `inputStream.readObject()`.

Из RequestThread вставил в цикл `sleep(60000)`, что снизило нагрузку до 0%.

**Comment by PovelikinRostislav** [comment]
На сервере добавил в schedulerthread и в server::responseThread sleep(60000) 
Твой подход мне понравился! Это снизит нагрузку, а на самом деле delay будет небольшой

**Comment by komarovn** [comment]
Здесь важно понимать, что ResponseThread на серере нужен лишь для того, чтобы один раз создать стримы. Вечный цикл по сути нужен только для поддержания жизни этого потока. Отправкой респонсов занимается другой поток, который вызывает метод отправки.
Исходя из этого, в принципе можно убрать вечный цикл и поставить `wait();`, т.к. он может спать всё время, пока мы не захотим его убить.

**Comment by PovelikinRostislav** [comment]
Это повод для подумать

**Comment by komarovn** [comment]
Done. 🐎
