### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by PovelikinRostislav** [PovelikinRostislav/client_server_app#36]
Коль, опиши, пожалуйста, как сейчас выглядит проект
Не хватает понимания технологий
К примеру, я не могу поменять класс Constants

**Comment by PovelikinRostislav** [comment]
1) Читай здесь про мавен: http://www.apache-maven.ru/index.html
2) .class файл - скомпилированный .java файл.
3) Скомпилированные файлы помещаются в директорию target. В этой папке ничего менять не нужно.
4) Весь код пишется в директории src. Скрипты SQL пишутся в директории scripts/sql (только в компоненте server-manager).

**Comment by komarovn** [comment]
5. Запустить проект можно из папки target, выполнив следующую команду:
`java -jar target.jar`
