### ISSUE TITLE
Bind database to our server side

### ISSUE THREAD

**Issue by komarovn** [PovelikinRostislav/client_server_app#39]
Привязать базу данных к выполнению операций на сервере.

**Comment by PovelikinRostislav** [comment]
Базовое соединение реализовано 
Необходимо модифицровать для создания более гибкого решения.

**Comment by komarovn** [comment]
Все операции над БД выполняем в DatabaseOperations через ServerThread.
Необходимые функции реализовываем в этом классе.

**Comment by komarovn** [comment]
Done. 🐔
