### ISSUE TITLE
Client side improvements

### ISSUE THREAD

**Issue by PovelikinRostislav** [PovelikinRostislav/client_server_app#5]
Заметил, что на стороне клиента:

- EXIT на GUI "выключает" поток - команды после вызова GUI не выполняются

- если сервер не поднят - клиент падает с connection refused. Надо так же сделать main loop thread, который будет опрашивать сервер и только после connection establishing: а) запустить GUI б) считать от пользователя token и другую информацию. в) передать ее на сервер. Если же сервер реально выключен - отвалить по таймауту и вывести в GUI форму, где написано, что приложение не будет работать по причине выключенного сервера.

https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html
Надо посмотреть документацию по socket'ам на Java: вероятно, там есть подобное. Я видел метод connect(), но он просит socketaddress удаленный. Как это связать - пока не знаю

**Comment by komarovn** [comment]
Done.
