### ISSUE TITLE
Make TCPServer and TCPClient abstract

### ISSUE THREAD

**Issue by komarovn** [PovelikinRostislav/client_server_app#7]
Сделать TCPServer и TCPClient абстрактными настолько, насколько это можно, т.е. такими, что они подойдут для любой задачи вне зависимости от того, какие данные мы посылаем.
Классы нужны только для того, чтобы создать подключение "клиент-сервер" и являются низшим уровнем в приложении.

**Comment by PovelikinRostislav** [comment]
Но посыл разных данных разве не подразумевает разные способы соединения?

**Comment by komarovn** [comment]
Данные лучше всего посылать одного конкретного вида. В нашем случае, насколько я могу видеть, нужно посылать некие объекты, представляющие собой request и response.
По идее получается, что TCPServer и TCPClient нужны только для установки соединения между друг другом и передачи "любых" данных. То есть мы сделать просто Input/OutputStream, оборачивать другие в них стримы (напр., ObjectInputStream).

**Comment by PovelikinRostislav** [comment]
Предлагаю сделать объектом передачи структуру из двух полей: 
-строка 
-Массив байт 

В строку записывается сообщение, которое читается на стороне клиента или сервера
А в массив байт помещается:
-Файл конфигурации​ серии экспериментов. Больше ни для чего это поле не нужно в принципе. 
Соответственно,если второе поле не null - значит сервер выводит на консоль сообщение из первого поля и пытается запустить серию экспериментов по конфиг файлу 
Если второе поле null, то просто выводит сообщение из первого поля 

А обратно сервер отправляет такие же объекты, только второе поле у него всегда null

**Comment by komarovn** [comment]
Структура придумается сама собой по мере написания программы. Вначале нам надо просто запихнуть туда token.

**Comment by komarovn** [comment]
Done.
