### ISSUE TITLE
Client side UI improvement

### ISSUE THREAD

**Issue by komarovn** [PovelikinRostislav/client_server_app#8]
Сделать открытие главной формы после ввода пользователем данных для входа (его имя).

**Comment by PovelikinRostislav** [comment]
+ переделать форму логина на ввод token только и передача его с формы на трэд, который обеспечивает connection со стороны клиента 

Главная форма со стороны клиента - что это? 
Output + кнопки отправки сообщения с вводом типа сообщения 
+ Отключиться 

Верно?

**Comment by komarovn** [comment]
В качестве токена предлагаю использовать имя (или псевдоним) пользователя. По нажатии кнопки формируется request, который летит на сервер. Далее сервер выдает какой-то ответ и отправляет response обратно клиенту.
Главная форма - форма, на которой располагается весь UI нашего приложения. Все остальные формы - вспомогательные (напр., форма входа).

**Comment by PovelikinRostislav** [comment]
UI на стороне сервера предполагается? 
Если да, то предлагаю разделять main frame на клиентский и серверный

**Comment by PovelikinRostislav** [comment]
Вид токена для нас не имеет никакой разницы, так как мы их не классифицируем - для нас это просто string, который мы в итоге хэшируем. 
Соответственно, мой concern был лишь на тему названия переменной в контроллере на стороне клиента и названия поля на main frame клиента 
И предложил я название : token

**Comment by komarovn** [comment]
Можно сделать UI на сервере с двумя кнопками: запустить и остановить. Запустить - запускает мэйн луп с листенером клиентов. Остановить - по факту метод написан, это stopServer, просто его надо довести до ума.
Другая функциональность на форме на данный момент не нужна (можно еще выводить окошко с логами, но это не самая важная задача сейчас).

**Comment by komarovn** [comment]
Заметка: после успешной отправки токена и прихода некого подтверждения нужно сделать подмену Scene и заменить primaryStage другим fxml интерфейсом.

**Comment by PovelikinRostislav** [comment]
Надо разработать UI на стороне клиента
Подробности можно увидеть в описании второго milestone

**Comment by komarovn** [comment]
Done.
